# Generated by Django 4.1.1 on 2022-09-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_place_alter_place_description_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='coordinates_lng',
            new_name='longitude',
        ),
    ]
