# Generated by Django 4.1.1 on 2022-09-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_rename_coordinates_lng_place_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='coordinates_lat',
            new_name='latitude',
        ),
    ]
